defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *defaults
  database: district_development

test:
  <<: *defaults
  database: district_test

production:
  <<: *defaults
  database: district_production
